### PR TITLE
FWI-1616 - Trivy can't fetch tags from quay.io

### PR DESCRIPTION
**Pull request by makoscafee**
This PR fixes #

## Checklist
* [ ] I have signed the CLA
* [ ] I have updated/added any relevant documentation

### What alternative solution should we consider, if any?

[Internal Ticket FWI-1616](https://fairwinds.myjetbrains.com/youtrack/issue/FWI-1616)

### CODE REVIEW

**Review by rbren — APPROVED** [review]
Thanks Barnie! Were you able to verify that recommendations are working for quay in the insights-agent? You should be able to see them in the `react-vulnerabilities` UI if you run it against staging

**Comment by makoscafee** [comment]
> Thanks Barnie! Were you able to verify that recommendations are working for quay in the insights-agent? You should be able to see them in the `react-vulnerabilities` UI if you run it against staging

i can see it can retrieve from quay now
```
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for docker.io/curlimages/curl:7.83.1"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/kube-controller-manager:v1.23.4"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for quay.io/fairwinds/nova:v3.2"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/kube-proxy:v1.23.4"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/etcd:3.5.1-0"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for docker.io/rancher/local-path-provisioner:v0.0.14"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/kube-scheduler:v1.23.4"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for quay.io/fairwinds/workloads:2.2"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/kube-apiserver:v1.23.4"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for quay.io/fairwinds/fw-trivy:bm-trivy-quay-tags"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for quay.io/fairwinds/insights-uploader:0.3"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for docker.io/kindest/kindnetd:v20211122-a2c10462"
time="2022-07-21T19:40:28Z" level=info msg="Started retrieving newest versions for k8s.gcr.io/coredns/coredns:v1.8.6"
time="2022-07-21T19:40:29Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/coredns/coredns:v1.8.6"
time="2022-07-21T19:40:29Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/etcd:3.5.1-0"
time="2022-07-21T19:40:29Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/kube-proxy:v1.23.4"
time="2022-07-21T19:40:29Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/kube-controller-manager:v1.23.4"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/kube-apiserver:v1.23.4"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for k8s.gcr.io/kube-scheduler:v1.23.4"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for docker.io/curlimages/curl:7.83.1"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for docker.io/kindest/kindnetd:v20211122-a2c10462"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/nova:v3.2"
time="2022-07-21T19:40:30Z" level=info msg="Finished retrieving newest versions for docker.io/rancher/local-path-provisioner:v0.0.14"
time="2022-07-21T19:40:31Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/insights-uploader:0.3"
time="2022-07-21T19:40:42Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/workloads:2.2"
time="2022-07-21T19:40:46Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/fw-trivy:bm-trivy-quay-tags"
```

**Comment by makoscafee** [comment]
here is the recommended tag from quay -> https://staging.insights.fairwinds.com/orgs/acme-co/react-vulnerabilities/image/sha256:e11c4e8c15621e2f45dec17010c81540ab37a197f4ee621bc1b746cfc4abe9e6?resolved=false&page=0&pageSize=25

**Comment by makoscafee** [comment]
added debug info and i can confirm we are fetching tags from quay now
```
time="2022-07-22T10:41:32Z" level=info msg="Fetched 435 tags for  quay.io/fairwinds/insights-uploader"
time="2022-07-22T10:41:32Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/insights-uploader:0.3"
time="2022-07-22T10:41:42Z" level=info msg="Fetched 2123 tags for  quay.io/fairwinds/workloads"
time="2022-07-22T10:41:43Z" level=info msg="Finished retrieving newest versions for quay.io/fairwinds/workloads:2.2"
time="2022-07-22T10:41:43Z" level=info msg="Fetched 2444 tags for  quay.io/fairwinds/fw-trivy"
```

**Pull request merged**
