### PR TITLE
Disable reports on CI/CD

### PR DESCRIPTION
**Pull request by baderbuddy**
## Description

Adds new configuration options to disable one report at a time.

## Checklist

* [x] I have updated the CHANGELOG of any plugins updated
* [x] I have updated the version file of any plugins updated
* [x] I have added tests wherever appropriate
* [x] I have labeled this PR with a label per plugin updated

### CODE REVIEW

**Comment by rbren** [comment]
I think Andy's issue still stands where it will try to pull the image, no?

**Comment by baderbuddy** [comment]
> I think Andy's issue still stands where it will try to pull the image, no?

@rbren I don't think so. It looks like images aren't actually pulled until the getTrivyReport function, so if he disabled Trivy then it shouldn't even attempt to pull.

**Comment by rbren** [comment]
🤔 don't we pull them in the insights-ci script?

**Comment by baderbuddy** [comment]
We only pull/save the ones that are specified as just "images" not ones from the manifests

**Comment by baderbuddy** [comment]
I'm pretty sure

**Comment by rbren** [comment]
nevermind, reread the message, I think you're right

**Pull request merged**
