### PR TITLE
Check Changelog on PR

### PR DESCRIPTION
**Pull request by baderbuddy**
Adds a new check to CI/CD to make sure Changelog is updated

### CODE REVIEW

**Comment by rbren** [comment]
Clever check! Thanks for doing this, I kept thinking about it and never got around to it 😄

**Review by rbren — APPROVED** [review]
oops never approved 🤦

**Comment by rbren** [comment]
Not sure what went wrong with e2e..

**Comment by baderbuddy** [comment]
Trivy data changes. The Prometheus PR has a fix in there.

**Pull request merged**
